services:
  express:
    build: ./express
    container_name: express-api
    ports:
      - "3001:3000"
    volumes:
      - ./express:/app              # monta todo el código
      - ./express/src/uploads:/app/uploads
    depends_on:
      - face-service
    restart: always

  face-service:
    build: ./face-service
    container_name: face-service
    ports:
      - "8000:8000"
    volumes:
      - ./face-service:/app         # monta todo el código
      - ./face-service/app/dataset:/app/dataset
    restart: always